include(":details")
include(":testingapp")
include(":appComponent")
include(":appdeps")
include(":di")
include(":homeScreen")
include(":repository")
include(":githubapi")
include( ":app")
rootProject.name = "DependecyInjection"